image: microsoft/dotnet:latest

stages:
  - build
  - test

variables:
  CASSANDRA_HOST: cassandra
  CASSANDRA_KEYSPACE: test

before_script:
  - dotnet restore

build:
  stage: build
  script:
    - dotnet build

test:
  stage: test

  services:
    - name: itsplus/s2shape-cassandra-test
      alias: cassandra

  script:
    - dotnet build
    - dotnet test
