image: microsoft/dotnet:latest

stages:
  - build
  - test

variables:
  CASSANDRA_HOST: cassandra
  CASSANDRA_KEYSPACE: test

before_script:
  - dotnet restore

build:
  stage: build
  script:
    - dotnet build

test:
  stage: test

  services:
    - cassandra:3.0

  script:
    - apt-get update && apt-get install -y python python-pip && pip install cqlsh
    - cqlsh -f CassandraSupplyCollectorTests/tests/data.sql $CASSANDRA_HOST
    - dotnet build
    - dotnet test
